spring.application.name=social-media-handler

# Server Port
server.port=8081

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/social_media_handler?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# autoconfigured if Drivers are defined in the database configuration
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Enable JPA repositories
spring.data.jpa.repositories.enabled=true

# ========================
# YouTube API configuration
# ========================
youtube.client-id=911034572316-same3rlcg9pt7k6mvo2rgtco0ve4u17c.apps.googleusercontent.com
youtube.client-secret=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
youtube.redirect-uri=http://localhost:8081/oauth/youtube/callback

# ===============================
# WhatsApp Cloud API Configuration
# ===============================
whatsapp.token=EAAVm0fubvs8BQaoSdatcz4pZCJQZCHF2Ou7fkuT6MnQ9hiY0xO9BrXRQT87CfKfAfkAM7eWciotMFZAfAGwrZAKkqmbYiCcGEpcQy2kyp0H02bbOMrMwWm6EfttVbBOW9pd3inq6QAAZClg9khAtjRbPlqM5HelWET8SwtDOKTBJzlLKHs6PyXrn6OkcCAkZA8IND5ZBCe0jJDmM1MhwR9Pqgb8n523mxy3jmIjoApuubTAHjuliCq1Jj0auv8lOka6GMlt4FIcdm59PQPbo843EcO6TwZDZD
whatsapp.phoneNumberId=914871318379881
whatsapp.apiUrl=https://graph.facebook.com/v17.0

# ======================
# EMAIL CONFIGURATION
# ======================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SENDER_MAIL}
spring.mail.password=${SENDER_MAIL_PASS}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# ======================
# LINKEDIN  CONFIGURATION
# ======================

linkedin.client-id=${LINKEDIN_CLIENT_ID}
linkedin.client-secret=${LINKEDIN_CLIENT_SECRET}
linkedin.redirect-uri=http://localhost:8081/oauth/linkedin/callback

# ==========================
# Pinterest Configuration
#===========================
pinterest.api.base-url=https://api.pinterest.com/v5
pinterest.access.token==${PINTEREST_TOKEN}
