
spring.application.name=social-media-handler

# Server Port
server.port=8082
# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/social_media_handler?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# autoconfigured if Drivers are defined in the database configuration
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Enable JPA repositories
spring.data.jpa.repositories.enabled=true

# ===============================
# WhatsApp Cloud API Configuration
# ===============================
whatsapp.token=EAAVm0fubvs8BQaZA2lpWsUvAIIgaZCN7cOKwOsaKfnZBHTDtRFNDZChByDcldsJxhTn1b91uoYrV5ztJrlsBszITrYnqd5wZBP2eyjAbfzUNw5Y2xM0p6yQhYdrZBGsFATX4TQobzxvYI9nsFTH3754GI8hE3ZAhgRVIhcqbJVlGtlyVc6GP7j8LvGZBD2lzhFRUFaLuLsOZBN8dJJr1xqjtJrufLE3JioQZCeufggZCwpZCUZBsqZBLnedPM1GT1ZAg1nWQ0hrh5VIxcC2sDJT3IMZBCAK4ZAIUAIxkZD
whatsapp.phoneNumberId=914871318379881
whatsapp.apiUrl=https://graph.facebook.com/v17.0
